notice("public interfaces: $::public_interfaces")
notice("public ipaddress: $::public_ipaddress")
notice("private interfaces: $::private_interfaces")
notice("private ipaddress: $::private_ipaddress")
notice("a interface: $::interface")
notice("a ip: $::ipaddress")
