name 'freequant-openshift_freequant'
version '0.0.1'

author 'Alex Lee, Freequant'
license 'ASL'
project_page 'https://github.com/javagg/puppet-openshift_freequant'
source 'git://github.com/javagg/puppet-openshift_freequant.git'
summary 'Module for installing Freequant Openshift'
description 'Configures OpenShift freequant nodes and support servers'
dependency 'openshift/openshift_origin', '>=0.1.18'
